#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH
# Test override: Skip the check for an existing n / npm / node installation.
export N_INSTALL_TEST_OVERRIDE_SKIP_EXISTING_INSTALLATION_TEST=1

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

# Create a temp. dir.
tmpDir=$(mktemp -d -t XXXX) || die # Works on both macOS and Linux; note: dir. name will have random extension on macOS (e.g., '.../XXXX.bJViLcM3') and none on Linux (e.g., '.../vXDA')
trap 'rm -rf "$tmpDir"' EXIT # Set up exit trap to automatically clean up the temp dir.


# With pre-existing dir:
N_PREFIX="$tmpDir" n-install -t || die "Preexisting empty dir: failed unexpectedly."

# With non-extant subfolder of pre-existing dir.
N_PREFIX="$tmpDir/foo/bar" n-install -t || die "Non-extant dir: failed unexpectedly."

